# Generated by Django 3.0.8 on 2020-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200703_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subreddit_following',
            field=models.ManyToManyField(blank=True, null=True, to='post.SubReddit'),
        ),
    ]
