# Generated by Django 3.0.8 on 2020-07-03 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20200703_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subreddit_following',
            field=models.ManyToManyField(blank=True, to='post.SubReddit'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='moderators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
