# Generated by Django 2.2.13 on 2020-07-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200717_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
