# Generated by Django 2.2.13 on 2020-08-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200810_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=5120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='post.Post'),
        ),
    ]
